Assignment2 cmalik
cmalik3595/PythonProject pull request #2
Opened 2022-09-22 05:21 UTC by cmalik3595

- Review comments from previous assignment
- Assignment number 2.

2022-09-22 22:57 UTC, Anujagagangras requested changes

2022-09-22 22:57 UTC, Anujagagangras commented on assignment2/baseball_assignment.sql
> +
It is taking longer time to execute rolling average part of the code. Please work on that part to fix it.

2022-09-23 02:22 UTC, Anujagagangras commented on assignment2/baseball_assignment.sql
> +
you can try rolling average using window function.

2022-09-24 03:13 UTC, cmalik3595 commented on assignment2/baseball_assignment.sql
> +
Added window function. Thanks for comment.

2022-09-24 03:15 UTC, cmalik3595 commented on assignment2/baseball_assignment.sql
> +
Separated slower algorithm from the main assignment.

2022-09-24 03:21 UTC, Anujagagangras approved these changes

2022-09-28 19:53 UTC, merged